// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCwfDNjisa3x-xrTxL6H2-GhRBQwlEiLM',
    appId: '1:76982828392:web:1e3817e01beb22777e2add',
    messagingSenderId: '76982828392',
    projectId: 'notentool',
    authDomain: 'notentool-6e2aa.firebaseapp.com',
    storageBucket: 'notentool.appspot.com',
  );

  // Run: flutterfire configure
}
